version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command:
            gradle test
      - store_test_results:
          path: test/test-results
      # - attach_workspace:
      #     at: /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - .       
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      #- checkout
      - attach_workspace:
          at: .  
      - run:
          name: Build
          command:
            gradle jar
      - store_artifacts:
          path: package/libs
          destination: prefix 
      - persist_to_workspace:
          root: .
          paths:
            - .      
workflows:
  version: 2
  flow:
    jobs:
      - test
      - package:
          requires:
            - test